<script setup lang="ts">
import {computed,nextTick,onMounted,ref} from 'vue';
import {checkoutLink,formatMoney,mutationCart,operation,request,validQuantity,type Cart,type Context,type Product,type User} from './api';
const context=ref<Context|null>(null),user=ref<User|null>(null),products=ref<Product[]>([]),categories=ref<{id:string;name:string}[]>([]);
const market=ref(''),search=ref(''),category=ref(''),cursor=ref<string|null>(null),hasNext=ref(false),count=ref(0),loading=ref(true),loadingMore=ref(false),error=ref(''),detailError=ref(''),pending=ref(false),switching=ref(false),detailLoading=ref(false),detailValid=ref(false);
const selected=ref<Product|null>(null),variantId=ref(''),quantity=ref(1),cart=ref<Cart|null>(null),authError=ref(''),authPending=ref(false),email=ref(''),password=ref('');
const detailDialog=ref<HTMLDialogElement|null>(null),bagDialog=ref<HTMLDialogElement|null>(null),authDialog=ref<HTMLDialogElement|null>(null);
let gridAbort:AbortController|undefined,detailAbort:AbortController|undefined,gridVersion=0,detailVersion=0;
const variant=computed(()=>selected.value?.variants.nodes.find(item=>item.id===variantId.value)||selected.value?.heroVariant||null);
const bagCount=computed(()=>cart.value?.lineItems.nodes.reduce((total,line)=>total+line.quantity,0)||0);
const checkout=computed(()=>cart.value?checkoutLink(cart.value.checkoutUrl):null);
const canAdd=computed(()=>!!variant.value?.price&&variant.value.availability?.availableForSale!==false&&validQuantity(quantity.value,variant.value)&&!pending.value&&!switching.value&&!detailLoading.value&&detailValid.value);
function message(value:unknown){return value instanceof Error?value.message:'Something went wrong. Please try again.';}
async function loadProducts(append=false){gridAbort?.abort();const controller=new AbortController();gridAbort=controller;const version=++gridVersion;error.value='';if(append)loadingMore.value=true;else{loading.value=true;products.value=[];cursor.value=null;hasNext.value=false;}
 try{const result=await operation<{data:{products:{nodes:Product[];pageInfo:{hasNextPage:boolean;endCursor:string|null};totalCount:number};categories:{nodes:{id:string;name:string}[]}}}>('ProductGrid',{...(search.value.trim()?{search:search.value.trim()}:{}),...(category.value?{categoryId:category.value}:{}),...(append&&cursor.value?{after:cursor.value}:{})},market.value||undefined,controller.signal);if(version!==gridVersion)return;products.value=append?[...products.value,...result.data.products.nodes]:result.data.products.nodes;categories.value=result.data.categories.nodes;cursor.value=result.data.products.pageInfo.endCursor;hasNext.value=result.data.products.pageInfo.hasNextPage;count.value=result.data.products.totalCount;}catch(value){if(!controller.signal.aborted&&version===gridVersion)error.value=message(value);}finally{if(version===gridVersion){loading.value=false;loadingMore.value=false;}}}
async function initialize(){loading.value=true;error.value='';try{context.value=await request<Context>('/context');if(context.value.authEnabled){const session=await request<{user:User|null}>('/auth/session');user.value=session.user;}await loadProducts();}catch(value){error.value=message(value);loading.value=false;}}
async function changeMarket(event:Event){const input=event.target as HTMLSelectElement;if(cart.value?.lineItems.nodes.length&&!window.confirm('Changing market clears your bag so all prices use the new market. Continue?')){input.value=market.value;return;}switching.value=true;market.value=input.value;cart.value=null;closeDetail();try{await loadProducts();}finally{switching.value=false;}}
async function openProduct(product:Product){detailAbort?.abort();const controller=new AbortController();detailAbort=controller;const version=++detailVersion;selected.value=product;variantId.value=product.heroVariant?.id||product.variants.nodes[0]?.id||'';quantity.value=variant.value?.quantityRule?.minimum||1;detailError.value='';detailLoading.value=true;detailValid.value=false;await nextTick();detailDialog.value?.showModal();try{const result=await operation<{data:{product:Product|null}}>('ProductDetail',{id:product.id},market.value||undefined,controller.signal);if(version!==detailVersion)return;if(!result.data.product)throw new Error('This product is no longer available.');selected.value=result.data.product;detailValid.value=true;variantId.value=result.data.product.heroVariant?.id||result.data.product.variants.nodes[0]?.id||'';quantity.value=variant.value?.quantityRule?.minimum||1;}catch(value){if(!controller.signal.aborted)detailError.value=message(value);}finally{if(version===detailVersion)detailLoading.value=false;}}
function cancelDetail(event:Event){if(pending.value){event.preventDefault();return;}closeDetail();}
function closeDetail(){detailAbort?.abort();detailVersion++;detailDialog.value?.close();selected.value=null;}
function changeVariant(){quantity.value=variant.value?.quantityRule?.minimum||1;}
async function showBag(){await nextTick();bagDialog.value?.showModal();}
async function addToBag(){if(!canAdd.value||!variant.value)return;pending.value=true;detailError.value='';const id=variant.value.id;try{if(!cart.value){const result=await operation<{data:{cartCreate:{cart:Cart|null;errors:{message?:string;__typename?:string}[]|null}}}>('CartCreate',{},market.value||undefined);cart.value=mutationCart(result.data.cartCreate);}const result=await operation<{data:{cartLineItemsAdd:{cart:Cart|null;errors:{message?:string;__typename?:string}[]|null}}}>('CartAddLine',{cartId:cart.value.id,variantId:id,quantity:quantity.value},market.value||undefined);cart.value=mutationCart(result.data.cartLineItemsAdd);closeDetail();await showBag();}catch(value){detailError.value=message(value);}finally{pending.value=false;}}
async function openAuth(){authError.value='';await nextTick();authDialog.value?.showModal();}
async function signIn(){authPending.value=true;authError.value='';try{const result=await request<{user:User}>('/auth/sign-in',{email:email.value,password:password.value});user.value=result.user;password.value='';cart.value=null;closeDetail();authDialog.value?.close();await loadProducts();}catch(value){authError.value=message(value);}finally{authPending.value=false;}}
async function signOut(){authPending.value=true;error.value='';try{await request('/auth/sign-out',{});user.value=null;cart.value=null;closeDetail();await loadProducts();}catch(value){error.value=message(value);}finally{authPending.value=false;}}
onMounted(initialize);
</script>
<template>
<div class="store-shell">
<header class="masthead"><a class="wordmark" href="#" aria-label="Store by Thor home" @click.prevent="category='';search='';loadProducts()">STORE <span>/ THOR</span></a><div class="header-actions"><label v-if="context?.markets.length" class="market-control"><span class="sr-only">Market</span><select :value="market" :disabled="pending||switching||authPending" @change="changeMarket"><option value="">{{ context.market }} · {{ context.currency }}</option><option v-for="item in context.markets" :key="item.id" :value="item.id">{{ item.label }} · {{ item.currency }}</option></select></label><template v-if="context?.authEnabled"><button v-if="!user" class="text-button account" :disabled="pending||switching" @click="openAuth">Sign in</button><button v-else class="text-button account" :disabled="authPending||pending||switching" @click="signOut">Sign out</button></template><button class="bag-button" @click="showBag">Bag <span>{{ bagCount }}</span></button></div></header>
<main><section class="intro"><p class="eyebrow">THE EVERYDAY COLLECTION</p><h1>Considered goods.</h1><div class="intro-bottom"><p>Useful things. Thoughtfully chosen.<br>Find your next everyday essential.</p><span>A collection for living well.</span></div></section>
<section class="catalog" aria-label="Product collection"><div class="catalog-toolbar"><nav aria-label="Categories"><button :class="{active:!category}" :disabled="switching" @click="category='';loadProducts()">All goods</button><button v-for="item in categories" :key="item.id" :class="{active:category===item.id}" :disabled="switching" @click="category=item.id;loadProducts()">{{ item.name }}</button></nav><form class="search" @submit.prevent="loadProducts()"><label class="sr-only" for="catalog-search">Search products</label><input id="catalog-search" v-model="search" placeholder="Find something good" type="search"><button aria-label="Search" :disabled="switching">↗</button></form></div><div class="catalog-meta"><span>{{ loading?'Discovering the collection':`${count} goods` }}</span><span>{{ switching?'Updating your market…':'Selected with intention' }}</span></div>
<div v-if="error" class="state-panel" role="alert"><p class="eyebrow">CONNECTION UNAVAILABLE</p><h2>We couldn’t load the collection.</h2><p>{{ error }}</p><button class="primary" @click="context?loadProducts():initialize()">Try again <span>↗</span></button></div>
<div v-else-if="loading" class="product-grid" aria-busy="true" aria-label="Loading products"><div v-for="item in 6" :key="item" class="skeleton"><div></div><span></span><span></span></div></div>
<div v-else-if="!products.length" class="state-panel"><p class="eyebrow">A LITTLE SPACE</p><h2>{{ search||category?'Nothing here just yet.':'The collection is on its way.' }}</h2><p>{{ search||category?'Try another search or explore all goods.':'There are no goods available in this market right now. Please come back soon.' }}</p><button v-if="search||category" class="primary" @click="search='';category='';loadProducts()">Explore all goods <span>↗</span></button></div>
<div v-else class="product-grid"><article v-for="product in products" :key="product.id" class="product"><button class="product-link" @click="openProduct(product)"><div class="product-image"><img v-if="product.heroVariant?.image" :src="product.heroVariant.image.src" :alt="product.heroVariant.image.altText||product.name" loading="lazy"><span v-else class="no-image">Image to come</span><span class="product-arrow" aria-hidden="true">↗</span></div><div class="product-heading"><h2>{{ product.name }}</h2><span>{{ product.heroVariant?.price?formatMoney(product.heroVariant.price.value):'Price unavailable' }}</span></div><p>{{ product.categories.nodes[0]?.name||'The collection' }}</p></button></article></div><div v-if="hasNext&&!error" class="load-more"><button class="outline" :disabled="loadingMore||switching" @click="loadProducts(true)">{{ loadingMore?'Loading…':'Discover more' }} <span>↓</span></button></div></section></main>
<footer><a class="wordmark" href="#">STORE <span>/ THOR</span></a><p>Good things, every day.</p><span>THE COLLECTION · {{ new Date().getFullYear() }}</span></footer>
<dialog ref="detailDialog" class="detail-dialog" aria-label="Product detail" @cancel="cancelDetail"><template v-if="selected"><button class="close-button" aria-label="Close product" :disabled="pending" @click="closeDetail">×</button><div class="detail-image"><img v-if="variant?.image" :src="variant.image.src" :alt="variant.image.altText||selected.name"><span v-else class="no-image">Image to come</span></div><div class="detail-content"><p class="eyebrow">{{ selected.categories.nodes[0]?.name||'THE COLLECTION' }}</p><h2>{{ selected.name }}</h2><p class="detail-price">{{ variant?.price?formatMoney(variant.price.value):'Price unavailable' }}</p><p class="description">{{ selected.description||'A considered addition to your everyday.' }}</p><label v-if="selected.variants.nodes.length>1" class="field">Choose an option<select v-model="variantId" :disabled="pending||detailLoading" @change="changeVariant"><option v-for="item in selected.variants.nodes" :key="item.id" :value="item.id">{{ item.name }}</option></select></label><p v-if="variant?.quantityRule" class="quantity-rule">Minimum {{ variant.quantityRule.minimum }}<template v-if="variant.quantityRule.maximum!==null"> · Maximum {{ variant.quantityRule.maximum }}</template> · Increments of {{ variant.quantityRule.increment }}</p><div class="add-row"><label class="quantity-field">Quantity<input v-model.number="quantity" type="number" :min="variant?.quantityRule?.minimum||1" :max="Math.min(variant?.quantityRule?.maximum??10000,10000)" :step="variant?.quantityRule?.increment||1" :disabled="pending||detailLoading"></label><button class="primary" :disabled="!canAdd" @click="addToBag">{{ pending?'Adding…':detailLoading?'Loading…':variant?.availability?.availableForSale===false?'Unavailable':'Add to bag' }} <span>+</span></button></div><p v-if="variant&&!validQuantity(quantity,variant)" class="inline-error">Choose a quantity within the available limits.</p><p v-if="detailError" class="inline-error" role="alert">{{ detailError }}</p><p class="detail-note">Your final total is confirmed in your bag.</p></div></template></dialog>
<dialog ref="bagDialog" class="drawer" aria-label="Shopping bag"><div class="drawer-heading"><h2>Your bag <span>({{ bagCount }})</span></h2><button class="close-button" aria-label="Close bag" @click="bagDialog?.close()">×</button></div><template v-if="cart?.lineItems.nodes.length"><div class="bag-lines"><article v-for="line in cart.lineItems.nodes" :key="line.id" class="bag-line"><img v-if="line.variant?.image" :src="line.variant.image.src" :alt="line.variant.image.altText||line.productName"><div v-else class="bag-placeholder"></div><div><h3>{{ line.productName }}</h3><p>{{ line.variantName }}</p><p>Quantity {{ line.quantity }} · {{ formatMoney(line.unitPrice.value) }} each</p><span>{{ formatMoney(line.total) }}</span></div></article></div><div class="bag-summary"><div><span>Subtotal</span><span>{{ formatMoney(cart.subtotal) }}</span></div><div class="bag-total"><span>Total</span><span>{{ formatMoney(cart.total) }}</span></div><p>Shipping and any applicable charges confirmed at checkout.</p><a v-if="checkout&&!pending&&!switching&&!authPending" :href="checkout" class="primary">Continue to checkout <span>↗</span></a><button v-else class="primary" disabled>{{ pending||switching||authPending?'Updating your bag…':'Checkout unavailable' }}</button><p v-if="!checkout" class="inline-error">The store has not provided a valid checkout link.</p></div></template><div v-else class="empty-bag"><span class="empty-symbol">＋</span><h3>Room for something good.</h3><p>Your bag is empty. Explore the collection and make it yours.</p><button class="primary" @click="bagDialog?.close()">Explore goods <span>↗</span></button></div></dialog>
<dialog ref="authDialog" class="auth-dialog" aria-label="Sign in"><button class="close-button" aria-label="Close sign in" @click="authDialog?.close()">×</button><p class="eyebrow">WELCOME BACK</p><h2>Your account.</h2><p>Sign in to see the collection for you.</p><form @submit.prevent="signIn"><label class="field">Email<input v-model="email" type="email" autocomplete="username" required :disabled="authPending"></label><label class="field">Password<input v-model="password" type="password" autocomplete="current-password" required :disabled="authPending"></label><p v-if="authError" role="alert" class="inline-error">{{ authError }}</p><button class="primary" :disabled="authPending">{{ authPending?'Signing in…':'Sign in' }} <span>↗</span></button></form></dialog>
</div>
</template>
