import { describe, expect, test } from 'bun:test';
import { createApp } from '../src/app';
import { readConfig, assertStorefrontUrl, ConfigError } from '../src/config';
const env={THOR_STOREFRONT_URL:'https://thor.example/storefront/graphql',THOR_ADMIN_URL:'https://thor.example/admin/graphql',THOR_ACCESS_TOKEN:'test-store-secret',THOR_ADMIN_API_KEY:'test-admin-secret',THOR_STORE_ID:'store_example',THOR_CHANNEL:'channel_nl',THOR_MARKET:'NL',THOR_CURRENCY:'EUR',THOR_MARKETS:JSON.stringify([{id:'NL',label:'Netherlands',channel:'channel_nl',country:'NL',currency:'EUR'},{id:'US',label:'United States',channel:'channel_us',country:'US',currency:'USD'}])};
function fixture(response:unknown={data:{products:{nodes:[]}}}){
 const calls:Array<{url:string;options:RequestInit;body:any}>=[];
 const fetcher=(async(url:string|URL|Request,options:RequestInit)=>{calls.push({url:String(url),options,body:JSON.parse(String(options.body))});return Response.json(response);}) as typeof fetch;
 return {app:createApp(readConfig(env),fetcher),calls};
}
const body=(data:unknown)=>({method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});
describe('closed operation boundary',()=>{
 for(const payload of [{operation:'AdminCollections'},{operation:'ProductGrid',query:'query { customer { accessToken } }'},{operation:'ProductGrid',upstream:'https://attacker.example'},{operation:'ProductGrid',variables:{query:'vendor:evil'}},{operation:'CartAddLine',variables:{cartId:'c',variantId:'v',quantity:0}}]){
 test(`rejects unsupported request ${JSON.stringify(payload)}`,async()=>{const {app,calls}=fixture();expect((await app.request('/storefront/graphql',body(payload))).status).toBe(400);expect(calls).toHaveLength(0);});
 }
 test('rejects arbitrary market IDs without contacting Thor',async()=>{const {app,calls}=fixture();expect((await app.request('/storefront/graphql',body({operation:'ProductGrid',marketId:'not-configured'}))).status).toBe(400);expect(calls).toHaveLength(0);});
 test('uses server document, selected market and only Storefront token',async()=>{const {app,calls}=fixture();const res=await app.request('/storefront/graphql',body({operation:'ProductGrid',marketId:'US',variables:{search:'lamp OR *',categoryId:'cat_lamps'}}));expect(res.status).toBe(200);expect(calls).toHaveLength(1);expect(calls[0].url).toBe(env.THOR_STOREFRONT_URL);expect(calls[0].body.operationName).toBe('ProductGrid');expect(calls[0].body.query).toStartWith('query ProductGrid');expect(calls[0].body.variables).toMatchObject({storeId:'store_example',priceChannelId:'channel_us',priceCountry:'US',priceCurrency:'USD',query:'"lamp OR *" AND category_id:"cat_lamps"'});expect(calls[0].options.headers).toMatchObject({'x-thor-storefront-token':'test-store-secret'});expect(JSON.stringify(calls[0].options.headers)).not.toContain('test-admin-secret');expect(await res.text()).not.toContain('secret');});
 test('uses buyer-specific configured price-channel mapping',async()=>{const config=readConfig({...env,THOR_COMPANY_LOCATION_ID:'agency_branch',THOR_COMPANY_PRICE_CHANNEL_ID:'channel_buyer'});let variables:any;const app=createApp(config,(async(_url,options)=>{variables=JSON.parse(String(options?.body)).variables;return Response.json({data:{product:null}});}) as typeof fetch);await app.request('/storefront/graphql',body({operation:'ProductDetail',variables:{id:'product_lamp'}}));expect(variables.priceChannelId).toBe('channel_buyer');expect(variables).not.toHaveProperty('companyLocationId');});
 test('cart creation uses the selected market context',async()=>{const {app,calls}=fixture({data:{cartCreate:{cart:{id:'cart'},errors:[]}}});await app.request('/storefront/graphql',body({operation:'CartCreate',marketId:'US'}));expect(calls[0].body.variables.input).toEqual({storeId:'store_example',priceChannelId:'channel_us',currency:'USD',countryCode:'US'});});
 test('only collections calls Admin with a separate API key',async()=>{const {app,calls}=fixture({data:{collections:{nodes:[]}}});expect((await app.request('/collections')).status).toBe(200);expect(calls[0].url).toBe(env.THOR_ADMIN_URL);expect(calls[0].options.headers).toMatchObject({'X-Api-Key':'test-admin-secret'});expect(JSON.stringify(calls[0].options.headers)).not.toContain('test-store-secret');});
 test('health/context never expose server credentials',async()=>{const {app,calls}=fixture();for(const path of ['/health','/context','/auth/session']){const res=await app.request(path);expect(res.status).toBe(200);expect(await res.text()).not.toContain('secret');}expect(calls).toHaveLength(0);});
 test('refuses browser requests from another origin',async()=>{const {app,calls}=fixture();expect((await app.request('/storefront/graphql',{...body({operation:'CartCreate'}),headers:{'Content-Type':'application/json',Origin:'https://attacker.example'}})).status).toBe(403);expect(calls).toHaveLength(0);});
 test('does not pass through sensitive upstream error text',async()=>{const {app}=fixture({errors:[{message:'test-admin-secret leaked by upstream'}]});const res=await app.request('/storefront/graphql',body({operation:'ProductGrid'}));expect(res.status).toBe(502);expect(await res.text()).not.toContain('test-admin-secret');});
 test('does not expose upstream GraphQL extensions',async()=>{const {app}=fixture({data:{product:null},extensions:{token:'secret'}});const res=await app.request('/storefront/graphql',body({operation:'ProductDetail',variables:{id:'p'}}));expect(await res.json()).toEqual({data:{product:null}});});
});
describe('startup configuration',()=>{
 for(const url of [undefined,'','   ']) test(`missing URL ${String(url)}`,()=>{try{assertStorefrontUrl({THOR_STOREFRONT_URL:url});throw new Error('guard did not fail');}catch(error){expect(error).toBeInstanceOf(ConfigError);expect((error as ConfigError).code).toBe('THOR_STOREFRONT_URL_REQUIRED');}});
 test('company location requires an explicit mapping',()=>{expect(()=>readConfig({...env,THOR_COMPANY_LOCATION_ID:'company'})).toThrow('buyer price-channel mapping');});
 test('rejects malformed market configuration',()=>{expect(()=>readConfig({...env,THOR_MARKETS:'not json'})).toThrow('JSON array');});
});
