// Host-only development/build config. TDK continues generating and using its
// own .autogenerated configs; never edit those files.
import { defineConfig } from 'vite';
import vue from '@vitejs/plugin-vue';
export default defineConfig({plugins:[vue()],base:'/storefront-web/',server:{host:'127.0.0.1',port:3300},build:{outDir:'dist'}});
