query ProductGrid($storeId:ID!, $priceChannelId:ID!, $priceCountry:String!, $priceCurrency:String!, $query:String, $after:String) { products(first:24,after:$after,query:$query,storeId:$storeId, priceChannelId:$priceChannelId, priceCountry:$priceCountry, priceCurrency:$priceCurrency) { nodes { id name slug description heroVariant { id name sku image { src altText } price { value { centAmount currencyCode fractionDigits } } availability { availableForSale: availableForPurchase availableQuantity } } variants(first:100) { nodes { id name sku image { src altText } price { value { centAmount currencyCode fractionDigits } } availability { availableForSale: availableForPurchase availableQuantity } } } categories(first:50) { nodes { id name } } } pageInfo { hasNextPage endCursor } totalCount } categories(first:50) { nodes { id name } } }
