query ProductPrice($storeId:ID!, $priceChannelId:ID!, $priceCountry:String!, $priceCurrency:String!, $id:ID!) { product(id:$id,storeId:$storeId, priceChannelId:$priceChannelId, priceCountry:$priceCountry, priceCurrency:$priceCurrency) { id name slug description heroVariant { id name sku image { src altText } price { value { centAmount currencyCode fractionDigits } } availability { availableForSale: availableForPurchase availableQuantity } } variants(first:100) { nodes { id name sku image { src altText } price { value { centAmount currencyCode fractionDigits } } availability { availableForSale: availableForPurchase availableQuantity } } } categories(first:50) { nodes { id name } } } }
